local module_instance = require("dragonbones.shared.instance")

local folder = "character4/Bicycle"
local skeleton_json = "/custom_res/" .. folder .. "_ske.json"
local tex_json      = "/custom_res/" .. folder .. "_tex.json"

function init(self)
	if profiler then
		profiler.enable_ui(true)
		profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)
	end
	
	msg.post(".", "acquire_input_focus")

	self.instance = nil
	local tbl = {
		skeleton_json = skeleton_json, 
		tex_json = tex_json,
	}

	msg.post("/BatchDragonModel", hash("load"), tbl)
end

local function update_world(self)
	timer.delay(1/30.0, true, function()
		msg.post("/BatchDragonModel", hash("update"), { dt = 1/30.0 })
	end)
end

function on_message(self, message_id, message)
	if message_id == hash("loaded") then
		update_world(self)
		self.instance = module_instance.instances[message.instance_no]
		if self.instance then
			print("Instance FPS", dragonbones.get_frame_rate(self.instance))
			--use game object for instance transform
			--[
				go.animate("/BatchDragonModel", "euler.z", go.PLAYBACK_LOOP_FORWARD, -359, 
				go.EASING_LINEAR, 2)
			--]]
			
			--dragonbones.add_event_callback(self.instance, function(me, tbl)
			--	pprint(tbl)
			--end)
			
			--dragonbones.set_slot_visibility(self.instance, "head", false)
			--dragonbones.set_flip_x(self.instance, true)
			--dragonbones.set_bone_rotation(self.instance, "root", math.rad(-60))
			--dragonbones.set_bone_position(self.instance, "root", 10, 30)
		end
	end
end

