local skeleton_json = resource.load("/custom_res/character4/Bicycle_ske.json")
local tex_json = resource.load("/custom_res/character4/Bicycle_tex.json")

local function create_buffer_prefix_name()
	math.random(os.clock())
	for i = 1, 4 do math.random(1, 10) end
	
	local tbl = {}
	local alphabet = "abcdefghijklmnopqrstuvwxyz0123456789"
	for i = 1, 20 do
		local pos = math.random(1, string.len(alphabet))
		table.insert(tbl, string.sub(alphabet, pos, pos))
	end
	return table.concat(tbl, "")
end

local function test(buffer_data)
	--local bt = buffer_data
	--pass
	--pprint(bt)

	--pass
	--Debugging: check positions, texCoord for reasonable data
	--[[local stream = buffer.get_stream(bt.buffer, hash("a_position")) --hash("a_position"), hash("a_texCoord")
	local offset = 1
	for i = 1, bt.buffer_count do
		print(i, stream[offset], stream[offset+1], stream[offset+2])
		offset = offset + 3
	end

	stream = buffer.get_stream(bt.buffer, hash("a_texCoord")) --hash("a_position"), hash("a_texCoord")
	offset = 1
	for i = 1, bt.buffer_count do
		print(i, stream[offset], stream[offset+1])
		offset = offset + 2
	end
	--]]

	for i, bt in ipairs(buffer_data) do
		if bt.name == "leg_upper" then
			local stream = buffer.get_stream(bt.indices, hash("indices")) 
			for j = 1, bt.indices_count ,3 do
				print(stream[j], stream[j+1], stream[j+2])
			end
			print("----------------------------------")
			stream = buffer.get_stream(bt.buffer_trilist, hash("a_position")) --hash("a_position"), hash("a_texCoord")
			local offset = 1
			for j = 1, bt.trilist_count do
				print(j, stream[offset], ",", stream[offset+1], ",", stream[offset+2], ",")
				offset = offset + 3
			end
			print("----------------------------------")
			stream = buffer.get_stream(bt.buffer_trilist, hash("a_texCoord")) --hash("a_position"), hash("a_texCoord")
			offset = 1
			for j = 1, bt.trilist_count do
				print(j, stream[offset], ",", stream[offset+1], ",")
				offset = offset + 2
			end
		end
	end
	
end


local function spawn_mesh(no)
	local z = -1 + 0.01 * no
	local id = factory.create("#factory", vmath.vector3(0, 0, z), nil, nil, vmath.vector3(1, 1, 1))
	return msg.url(nil, id, "mesh" )
end

local function set_mesh_data(self, mesh_no, buffer_data)
	--pprint(buffer_data.mtx_model)
	local mesh_id = self.meshes[mesh_no]
	--print(mesh_id)
	
	go.set(mesh_id, hash("u_mtx_mvp"),     buffer_data.mtx_mvp)
	--go.set(mesh_id, hash("u_mtx_model"),   buffer_data.mtx_model)
	--go.set(mesh_id, hash("u_mtx_view"),    buffer_data.mtx_view)
	local buffer_name = self.buffer_prefix_name .. tostring(mesh_no) .. ".bufferc"
	
	--local my_buffer = resource.create_buffer(buffer_name, 
	--{ buffer = buffer_data.buffer }) --triangles_list

	local my_buffer
	if self.current_buffers[mesh_no] then
		my_buffer = self.current_buffers[mesh_no]
		resource.set_buffer(my_buffer, buffer_data.buffer_trilist)
	else
		my_buffer = resource.create_buffer(buffer_name, { buffer = buffer_data.buffer_trilist }) 
		--triangles resource.
	end

	go.set(mesh_id, hash("vertices"), my_buffer )
	self.current_buffers[mesh_no] = my_buffer
end

local function update_db_world(self)
	--release previous buffers
	
	
	--update animation and get buffers
	dragonbones.update(self.instance, 1/30.0)
	local buffer_table = dragonbones.get_buffers(self.instance)
	--test(buffer_table)

	--Set mesh vertices and vertex constants
	for k,v in ipairs(buffer_table) do
		set_mesh_data(self, k, v)
		--test(v)
		--if k == 3 then break end
	end

	--free resources, IMPORTANT!
	collectgarbage("collect")
end

function init(self)
	msg.post(".", "acquire_input_focus")

	profiler.enable_ui(true)
	profiler.set_ui_view_mode(profiler.VIEW_MODE_MINIMIZED)

	--initiate dragon bones and upload json data
	self.instance = dragonbones.create(1600, 1200)
	dragonbones.load_data(self.instance, skeleton_json, tex_json)
	

	self.buffer_prefix_name = "/" .. create_buffer_prefix_name()
	self.current_buffers = {}
	self.meshes  = {}

	local no_slots = dragonbones.get_no_slots(self.instance)
	for i = 1, no_slots do
		local mesh_id = spawn_mesh(i)
		table.insert(self.meshes, mesh_id)
	end

	local tbl_animations = dragonbones.get_anination_names(self.instance)
	--pprint(tbl_animations)
	dragonbones.fade_in_animation(self.instance, tbl_animations[1], 0, 0, 0)
	dragonbones.set_world_translation(self.instance, 0, 200)

	self.buffer_prefix_name = "/" .. create_buffer_prefix_name()
	update_db_world(self)
	--[
	timer.delay(1/30, true, function()
		--print("Updating  .........................................")
		self.buffer_prefix_name = "/" .. create_buffer_prefix_name()
		update_db_world(self)
	end)
	--]]
	
	
end
