go.property("u_texture", resource.texture())

local mod_instances = require("dragonbones.shared.instance")


local function spawn_mesh(self)
	--local z = 0 + 0.01 * no
	local id = factory.create("#factory") --, vmath.vector3(0, 0, z))
	local mesh_id =  msg.url(nil, id, "mesh" )
	go.set_parent(id, ".")

	if self.texture_name then
		local tex = mod_instances.textures[self.texture_name]
		go.set(mesh_id, "texture0",  tex)
	else
		go.set(mesh_id, "texture0",  hash(self.u_texture))
	end
	
	return mesh_id
end

local function set_mesh_data(self, buffer_data)
	local my_buffer = mod_instances.buffers[self.instance_name]
	if my_buffer then
		resource.set_buffer(my_buffer, buffer_data.batch_buffer)
	else
		local success, new_buffer = pcall(function ()
			return resource.create_buffer(self.buffer_name, { buffer = buffer_data.batch_buffer }) 
		end)
		if not success then
			print("Mesh buffer name already used.")
			return
		end
		mod_instances.buffers[self.instance_name] = new_buffer 
		my_buffer = new_buffer
	end

	go.set(self.mesh_id, hash("vertices"), my_buffer )
end

local function update_db_world(self)
	--update animation and get buffers
	--
	--local scale, rotation, translation
	self.scale   = go.get_world_scale(".")
	self.rotation = go.get_world_rotation(".")
	self.translation = go.get_world_position(".")
	
	go.set(self.mesh_id, hash("scale"), self.scale)
	go.set(self.mesh_id, hash("rotation"), self.rotation)
	go.set(self.mesh_id, hash("translation"), self.translation)
	--]]
	
	dragonbones.update(self.instance, self.dt)
	local buffer_table = dragonbones.get_batch_buffer(self.instance)
	--pprint(buffer_table)

	set_mesh_data(self,  buffer_table)

	--free resources, IMPORTANT!
	collectgarbage("step", 1)
end

local function load_world(self)
	local skeleton_json = resource.load(self.skeleton_json)
	local tex_json      = resource.load(self.tex_json)

	--initiate dragon bones and upload json data
	self.dt = 1/30.0
	self.scale = vmath.vector4(1.0)
	self.rotation = vmath.vector4(1.0)
	self.translation = vmath.vector4(1.0)

	
	self.instance = dragonbones.create()
	mod_instances.instances[self.instance_name] = self.instance
	
	dragonbones.load_data(self.instance, skeleton_json, tex_json)


	--dragonbones.get_no_slots(self.instance)
	self.mesh_id = spawn_mesh(self)

	local tbl_animations = dragonbones.get_anination_names(self.instance)
	--pprint(tbl_animations)
	dragonbones.fade_in_animation(self.instance, tbl_animations[1])

	if self.enabled then
		update_db_world(self)
	end
	self.loaded = true
end



function on_message(self, message_id, message, sender)
	if message_id == hash("load") then
		self.skeleton_json = message.skeleton_json
		self.tex_json = message.tex_json
		self.texture_name = message.texture_name
		self.instance_name =  message.buffer_prefix
		self.enabled = true
		self.buffer_name  = "/" .. self.instance_name .. ".bufferc"
		self.owner = sender

		load_world(self)
		msg.post(sender, "loaded", {instance_name = self.instance_name})
	elseif message_id == hash("update") then
		if self.enabled then
			self.dt = message.dt or self.dt
			if self.instance then
				update_db_world(self)
			end
		end
	elseif message_id == hash("disable") then
		self.enabled = not message.disable
		local str_enable = self.enabled and "enable" or "disable"
		msg.post(self.mesh_id,  str_enable)
	elseif message_id == hash("swap_texture") then
		local tex = mod_instances.textures[message.texture_name]
		if tex then
			go.set(self.mesh_id, "texture0",  tex)
		end
	elseif message_id == hash("tint") then
		go.set(self.mesh_id, hash("tint"), message.tint)
	end
end

function final(self)
	--let lua gc take care
end
